/**
 * @file Automatically generated by catalyst-channel-list.
 */

export enum ArbitraryMessagingBridge {
  Mock = 'MOCK',
  Wormhole = 'Wormhole',
  Layerzero = 'Layerzero',
  Polymer = 'Polymer',
  Default = 'default',
}
