/**
 * @file Automatically generated by catalyst-channel-list.
 */

export const chainsName = {
  "sepolia": "11155111",
  "arbitrumsepolia": "421614",
  "optimismsepolia": "11155420",
  "basesepolia": "84532",
  "blasttestnet": "168587773"
};

export const reverseChainsName = {
  "84532": "basesepolia",
  "421614": "arbitrumsepolia",
  "11155111": "sepolia",
  "11155420": "optimismsepolia",
  "168587773": "blasttestnet"
};