/**
 * @file Automatically generated by catalyst-channel-list.
 */

export const chainsName: Record<string, string> = {
  "sepolia": "11155111",
  "arbitrumsepolia": "421614",
  "optimismsepolia": "11155420",
  "basesepolia": "84532",
  "mantlesepolia": "5003",
  "blasttestnet": "168587773",
  "scrollsepolia": "534351",
  "seidevnet": "713715",
  "xaitestnet": "37714555429",
  "arbitrum": "42161",
  "optimism": "10",
  "base": "8453",
  "blast": "81457",
  "sei": "1329",
  "xai": "660279",
  "mantle": "5000",
  "scroll": "534352"
};

export const reverseChainsName: Record<string, string> = {
  "10": "optimism",
  "1329": "sei",
  "5000": "mantle",
  "5003": "mantlesepolia",
  "8453": "base",
  "42161": "arbitrum",
  "81457": "blast",
  "84532": "basesepolia",
  "421614": "arbitrumsepolia",
  "534351": "scrollsepolia",
  "534352": "scroll",
  "660279": "xai",
  "713715": "seidevnet",
  "11155111": "sepolia",
  "11155420": "optimismsepolia",
  "168587773": "blasttestnet",
  "37714555429": "xaitestnet"
};