import * as fs from 'fs';
import * as path from 'path';

export const fileHeader = `/**
 * @file Automatically generated by catalyst-channel-list.
 */\n
`;

export function capatalise(val: string): string {
  let lower = val.toLowerCase();
  let caped = lower[0].toUpperCase() + lower.slice(1);
  return caped;
}

export function write(localPath: string, val: string, description: string = '') {
  fs.writeFile(path.join(__dirname, localPath), val, (err) => {
    if (err) {
      console.error(`Error writing ${description} to file: ${err} `);
    } else {
      console.log(`${description} generated successfully`);
    }
  });
}

export function generateEnum(enumName: string, values: string[]): string {
  let enumStr = `export enum ${enumName} {\n`;
  for (const key in values) {
    enumStr += `  ${capatalise(values[key])} = '${values[key]}',\n`;
  }
  enumStr += '}\n';
  return enumStr;
}
